name: flutter_textgrid
description: Handle Praat TextGrid's format in pure Dart
version: 0.0.1
homepage: unina.it

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bisection: ^0.4.3+1
  collection: ^1.17.1

dev_dependencies:
  build_runner: ^2.4.6
  test: ^1.24.6
